# Generated by Django 5.2 on 2025-05-02 15:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasUnidadconstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, max_length=10, null=True)),
                ('total_plantas', models.IntegerField(blank=True, null=True)),
                ('anio_construccion', models.IntegerField(blank=True, null=True)),
                ('area_construida', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('estado_conservacion', models.CharField(blank=True, max_length=50, null=True)),
                ('local_id', models.CharField(blank=True, max_length=100, null=True)),
                ('avaluo_unidad', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caracteristicas_unidadconstruccion',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColDocumentotipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'col_documentotipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColEstadodisponibilidadtipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'col_estadodisponibilidadtipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColFuenteadministrativatipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'col_fuenteadministrativatipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColInteresadotipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'col_interesadotipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColRelacionsuperficietipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'col_relacionsuperficietipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColUnidadadministrativabasicatipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'col_unidadadministrativabasicatipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrAutoreconocimientoetnicotipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cr_autoreconocimientoetnicotipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrCondicionprediotipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cr_condicionprediotipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrConstruccionplantatipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cr_construccionplantatipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrDerechotipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cr_derechotipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrDestinacioneconomicatipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cr_destinacioneconomicatipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrEstadotipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cr_estadotipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrMutaciontipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cr_mutaciontipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrPrediotipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cr_prediotipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrSexotipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cr_sexotipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrUnidadconstrucciontipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cr_unidadconstrucciontipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrUsouconstipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('itfcode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cr_usouconstipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Derecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraccion_derecho', models.DecimalField(decimal_places=5, max_digits=20)),
                ('naturaleza_juridica', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_naturaleza_juridica', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha_anotacion', models.DateField(blank=True, null=True)),
                ('comienzo_vida_util_version', models.DateField(null=True)),
                ('fin_vida_util_version', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'derecho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnteEmisortipo',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ente_emisortipo',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoAsignacion',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado_asignacion',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoRadicado',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado_radicado',
                'ordering': ['ilicode'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstructuraAvaluo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_avaluo', models.DateField()),
                ('avaluo_catastral', models.BigIntegerField(blank=True, null=True)),
                ('vigencia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estructura_avaluo',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuenteAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina_origen', models.IntegerField(blank=True, null=True)),
                ('ciudad_origen', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_documento_fuente', models.DateField(blank=True, null=True)),
                ('local_id', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'fuente_administrativa',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('autoreconocimientocampesino', models.BooleanField(blank=True, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=255, null=True)),
                ('comienzo_vida_util_version', models.DateField(null=True)),
                ('fin_vida_util_version', models.DateField(blank=True, null=True)),
                ('local_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'interesado',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InteresadoPredio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'interesado_predio',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=3)),
                ('codigo_orip', models.CharField(blank=True, max_length=4, null=True)),
                ('matricula_inmobiliaria', models.IntegerField(blank=True, null=True)),
                ('numero_predial_nacional', models.CharField(max_length=30)),
                ('codigo_homologado', models.CharField(max_length=11)),
                ('area_catastral_terreno', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('vigencia_actualizacion_catastral', models.DateField()),
                ('comienzo_vida_util_version', models.DateField(null=True)),
                ('fin_vida_util_version', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'predio',
                'ordering': ['numero_predial_nacional'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PredioFuenteadministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'predio_fuenteadministrativa',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PredioTramitecatastral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'predio_tramitecatastral',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PredioUnidadespacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'predio_unidadespacial',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Radicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_radicado', models.CharField(max_length=30)),
                ('fecha_radicado', models.DateField()),
            ],
            options={
                'db_table': 'radicado',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadicadoPredioAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'radicado_predio_asignado',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comienzo_vida_util_version', models.DateField(null=True)),
                ('fin_vida_util_version', models.DateField(blank=True, null=True)),
                ('geometria', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=9377)),
                ('local_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'terreno',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TerrenoZonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_catastral_terreno', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('avaluo_terreno', models.BigIntegerField(blank=True, null=True)),
                ('zona_fisica', models.IntegerField(blank=True, null=True)),
                ('zona_geoeconomica', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'terreno_zonas',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TramiteCatastral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_resolucion', models.CharField(max_length=30)),
                ('fecha_resolucion', models.DateField()),
                ('fecha_inscripcion', models.DateField()),
                ('comienzo_vida_util_version', models.DateField(null=True)),
                ('fin_vida_util_version', models.DateField(blank=True, null=True)),
                ('radicado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tramite_catastral',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidadconstruccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta_ubicacion', models.IntegerField(blank=True, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('comienzo_vida_util', models.DateField()),
                ('fin_vida_util', models.DateField(blank=True, null=True)),
                ('geometria', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=9377)),
                ('local_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'unidadconstruccion',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
