# Generated by Django 5.2 on 2025-05-03 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catastro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='radicadopredioasignado',
            name='usuario_analista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='radicado_analista', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radicadopredioasignado',
            name='usuario_coordinador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='radicado_coordinador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prediotramitecatastral',
            name='radicado_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catastro.radicadopredioasignado'),
        ),
        migrations.AddField(
            model_name='terreno',
            name='relacion_superficie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catastro.colrelacionsuperficietipo'),
        ),
        migrations.AddField(
            model_name='prediounidadespacial',
            name='terreno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catastro.terreno'),
        ),
        migrations.AddField(
            model_name='terrenozonas',
            name='terreno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catastro.terreno'),
        ),
        migrations.AddField(
            model_name='tramitecatastral',
            name='mutacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catastro.crmutaciontipo'),
        ),
        migrations.AddField(
            model_name='tramitecatastral',
            name='radicado_asignado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catastro.radicadopredioasignado'),
        ),
        migrations.AddField(
            model_name='prediotramitecatastral',
            name='tramite_catastral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catastro.tramitecatastral'),
        ),
        migrations.AddField(
            model_name='unidadconstruccion',
            name='caracteristicas_unidadconstruccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catastro.caracteristicasunidadconstruccion'),
        ),
        migrations.AddField(
            model_name='unidadconstruccion',
            name='tipo_planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catastro.crconstruccionplantatipo'),
        ),
        migrations.AddField(
            model_name='prediounidadespacial',
            name='unidadconstruccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catastro.unidadconstruccion'),
        ),
        migrations.AddIndex(
            model_name='predio',
            index=models.Index(fields=['estado', 'id'], name='predio_estado__87bc03_idx'),
        ),
        migrations.AddIndex(
            model_name='interesadopredio',
            index=models.Index(fields=['predio'], name='interesado__predio__7d1186_idx'),
        ),
        migrations.AddIndex(
            model_name='estructuraavaluo',
            index=models.Index(fields=['predio'], name='estructura__predio__7d8eef_idx'),
        ),
        migrations.AddIndex(
            model_name='radicado',
            index=models.Index(fields=['id', 'numero_radicado'], name='radicado_id_883ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='tramitecatastral',
            index=models.Index(fields=['numero_resolucion', 'fecha_resolucion', 'radicado', 'mutacion'], name='tramite_cat_numero__b934e0_idx'),
        ),
    ]
