# Generated by Django 5.2 on 2025-04-27 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicasunidadconstruccion',
            name='avaluo_unidad',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristicasunidadconstruccion',
            name='area_construida',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristicasunidadconstruccion',
            name='total_plantas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predio',
            name='area_catastral_terreno',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='unidadconstruccion',
            name='planta_ubicacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TerrenoZonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_catastral_terreno', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('avaluo_terreno', models.BigIntegerField(blank=True, null=True)),
                ('zona_fisica', models.IntegerField(blank=True, null=True)),
                ('zona_geoeconomica', models.IntegerField(blank=True, null=True)),
                ('terreno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catastro.terreno')),
            ],
            options={
                'db_table': 'terreno_zonas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EstructuraAvaluo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_avaluo', models.DateField()),
                ('avaluo_catastral', models.BigIntegerField(blank=True, null=True)),
                ('vigencia', models.IntegerField(blank=True, null=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catastro.predio')),
                ('predio_tramitecatastral', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catastro.prediotramitecatastral')),
            ],
            options={
                'db_table': 'estructura_avaluo',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['predio'], name='estructura__predio__7d8eef_idx')],
            },
        ),
    ]
