# Generated by Django 5.2 on 2025-04-27 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilicode', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario_rol',
                'ordering': ['ilicode'],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usuarios_groups', related_query_name='user', to='auth.group')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='login.usuariorol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuarios_user_permissions', related_query_name='user', to='auth.permission')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['rol', 'id'], name='usuarios_rol_id_7f208e_idx')],
            },
        ),
    ]
