# Generated by Django 5.2 on 2025-05-02 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialLogueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha con la cual se creo el registro', verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha con la cual se modifico el objeto', verbose_name='modified at')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
